name: Agent framework CI

on:
  push:

jobs:
  package-mypy:
    name: "Framework: mypy"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./agent_framework
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version-file: './agent_framework/pyproject.toml'
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install
      - name: Run mypy
        run: poetry run mypy --show-column-numbers --show-absolute-path --no-pretty .

  package-ruff:
    name: "Framework: ruff"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./agent_framework
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version-file: './agent_framework/pyproject.toml'
          cache: 'poetry'
      - name: Install dependencies
        run: pip install ruff
      - name: Run Ruff
        run: ruff check --output-format=github
